/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as BateauxRouteImport } from './routes/bateaux'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CruisesIndexRouteImport } from './routes/cruises.index'
import { Route as TierSlugRouteImport } from './routes/tier.$slug'
import { Route as CruisesIdRouteImport } from './routes/cruises.$id'

const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const BateauxRoute = BateauxRouteImport.update({
  id: '/bateaux',
  path: '/bateaux',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CruisesIndexRoute = CruisesIndexRouteImport.update({
  id: '/cruises/',
  path: '/cruises/',
  getParentRoute: () => rootRouteImport,
} as any)
const TierSlugRoute = TierSlugRouteImport.update({
  id: '/tier/$slug',
  path: '/tier/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CruisesIdRoute = CruisesIdRouteImport.update({
  id: '/cruises/$id',
  path: '/cruises/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bateaux': typeof BateauxRoute
  '/compare': typeof CompareRoute
  '/guide': typeof GuideRoute
  '/cruises/$id': typeof CruisesIdRoute
  '/tier/$slug': typeof TierSlugRoute
  '/cruises/': typeof CruisesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bateaux': typeof BateauxRoute
  '/compare': typeof CompareRoute
  '/guide': typeof GuideRoute
  '/cruises/$id': typeof CruisesIdRoute
  '/tier/$slug': typeof TierSlugRoute
  '/cruises': typeof CruisesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bateaux': typeof BateauxRoute
  '/compare': typeof CompareRoute
  '/guide': typeof GuideRoute
  '/cruises/$id': typeof CruisesIdRoute
  '/tier/$slug': typeof TierSlugRoute
  '/cruises/': typeof CruisesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bateaux'
    | '/compare'
    | '/guide'
    | '/cruises/$id'
    | '/tier/$slug'
    | '/cruises/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bateaux'
    | '/compare'
    | '/guide'
    | '/cruises/$id'
    | '/tier/$slug'
    | '/cruises'
  id:
    | '__root__'
    | '/'
    | '/bateaux'
    | '/compare'
    | '/guide'
    | '/cruises/$id'
    | '/tier/$slug'
    | '/cruises/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BateauxRoute: typeof BateauxRoute
  CompareRoute: typeof CompareRoute
  GuideRoute: typeof GuideRoute
  CruisesIdRoute: typeof CruisesIdRoute
  TierSlugRoute: typeof TierSlugRoute
  CruisesIndexRoute: typeof CruisesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bateaux': {
      id: '/bateaux'
      path: '/bateaux'
      fullPath: '/bateaux'
      preLoaderRoute: typeof BateauxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cruises/': {
      id: '/cruises/'
      path: '/cruises'
      fullPath: '/cruises/'
      preLoaderRoute: typeof CruisesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tier/$slug': {
      id: '/tier/$slug'
      path: '/tier/$slug'
      fullPath: '/tier/$slug'
      preLoaderRoute: typeof TierSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cruises/$id': {
      id: '/cruises/$id'
      path: '/cruises/$id'
      fullPath: '/cruises/$id'
      preLoaderRoute: typeof CruisesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BateauxRoute: BateauxRoute,
  CompareRoute: CompareRoute,
  GuideRoute: GuideRoute,
  CruisesIdRoute: CruisesIdRoute,
  TierSlugRoute: TierSlugRoute,
  CruisesIndexRoute: CruisesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
